name: conda-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3
  - r-base=4.1
  - r-biocmanager=1.30.16
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics
  - bioconductor-limma
  - bioconductor-go.db
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
